config/routes.rb
Rails.application.routes.draw do
  get 'reservation/new'
  root "static_pages#home"
  resources :reservation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validates :number, numericality: { greater_than_or_equal_to: 1 }
    validates :accommodation, numericality: { greater_than_or_equal_to: 1 }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
  def new
    @reservation_user = Reservation.new
    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def 
    home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TagawaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservation/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>田川伊田駅舎ホテル 予約表</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<h1>予約フォーム</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @reservation, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :name, "お名前" %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :date, "日付" %>
        <%= f.date_field :date, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :checkin_time, "チェックイン時間" %>
        <%= f.select :checkin_time, (15..22).map { |h| ["#{h}:00", "#{h}:00"] }, {}, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :number, "人数" %>
        <div class="btn-group" role="group" aria-label="人数選択">
          <% (1..4).each do |num| %>
            <%= f.radio_button :number, num, class: 'btn-check' %>
            <%= f.label "number_#{num}", num, class: 'btn btn-outline-primary' %>
          <% end %>
        </div>
        <%= f.number_field :number, min: 1, class: 'form-control mt-2' %>
      </div>

      <div class="form-group">
        <%= f.label :accommodation, "宿泊数" %>
        <div class="btn-group" role="group" aria-label="宿泊数選択">
          <% (1..4).each do |num| %>
            <%= f.radio_button :accommodation, num, class: 'btn-check' %>
            <%= f.label "accommodation_#{num}", num, class: 'btn btn-outline-primary' %>
          <% end %>
        </div>
        <%= f.number_field :accommodation, min: 1, class: 'form-control mt-2' %>
      </div>

      <div class="form-group">
        <%= f.label :price, "料金" %>
        <div class="btn-group" role="group" aria-label="料金選択">
          <% [4200, 5040].each do |price| %>
            <%= f.radio_button :price, price, class: 'btn-check' %>
            <%= f.label "price_#{price}", "#{price}円", class: 'btn btn-outline-primary' %>
          <% end %>
        </div>
        <%= f.number_field :price, min: 0, class: 'form-control mt-2' %>
      </div>

      <%= f.submit "予約する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>田川伊田駅舎ホテル 予約表</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <h1>田川伊田駅舎ホテル 予約表</h1>

  <div class="days">
    <%= date_field_tag :date %>
    <%= button_tag "assign", onclick: "assign_button()" %>
    <%= button_to "予約追加", onclick: "click3()" %>
    <%= button_to "キャンセル/変更", new_reservation_path, method: :get %>
    <%= button_tag "設定", onclick: "host_setting()" %>
  </div>

  <div class="reserve"></div>

  <% room_colors = {
    "1" => "4682b4",
    "2" => "4682b4",
    "3" => "4682b4",
    "4" => "3cb371",
    "5" => "3cb371",
    "6" => "fa8072",
    "7" => "fa8072",
    "8" => "3cb371",
    "9" => "3cb371",
    "10" => "4682b4",
    "11" => "4682b4"
  } %>

  <% (1..11).each do |room_number| %>
    <div class="table<%= room_number %>">
      <table border="2" width="420">
        <tr align="center">
          <td rowspan="3" width="20%" bgcolor="<%= room_colors[room_number.to_s] %>"><%= room_number %>号室</td>
          <td width="10%">名前</td>
          <td colspan="2" width="50%"><span id="table<%= room_number %>_name"></span></td>
          <td width="10">人数</td>
          <td width="10"><span id="table<%= room_number %>_number"></span></td>
        </tr>
        <tr align="center">
          <td colspan="1">時間</td>
          <td width="20"><span id="table<%= room_number %>_time"></span></td>
          <td width="10" colspan="3"><span id="table<%= room_number %>_daynumber">拍</span></td>
        </tr>
        <tr align="center">
          <td colspan="2"><span id="table<%= room_number %>_price">円</span></td>
          <td>決済方法</td>
          <td colspan="2">
            <%= select_tag "way#{room_number}",
              options_for_select([
                ["", "0"],
                ["クレジット", "1"],
                ["事前支払い", "2"],
                ["PayPay", "3"],
                ["現金", "4"]
              ]),
              id: "sum_way#{room_number}"
            %>
          </td>
        </tr>
      </table>
    </div>
  <% end %>

  <div class="tablesum">
    <table border="2" width="220">
      <% [
        ["総売上", "total_price"],
        ["事前支払い売上", "before_price"],
        ["PayPay売上", "paypay_price"],
        ["現金売上", "money_price"],
        ["クレジット売上", "credit_price"],
        ["宿泊税", "tax_price"],
        ["人数", "number_price"],
        ["客単価", "numberof_price"]
      ].each do |label, id| %>
        <tr align="center">
          <td><%= label %></td>
          <td><span id="<%= id %>"></span></td>
        </tr>
      <% end %>
    </table>
  </div>
</body>
</html>